---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofrecord
  namespace: algorithm-open
spec:
  selector:
    matchLabels:
      app: ofrecord
  replicas: 1
  template:
    metadata:
      labels:
        app: ofrecord
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
      - name: ofrecord
        image: harbor.dubhe.ai/dataset/ofrecord:v1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["test","-e","/root/.startup"]
        command: ["/bin/bash","-c","cd /dubhe_data_process && python main.py ofrecord True 127.0.0.1,6379,10,'Tianshu@123'"]
        volumeMounts:
        - name: ofrecord-fs
          mountPath: /nfs
        - name: dubhe-data-process
          mountPath: /dubhe_data_process  
        ports:
        - containerPort: 9898
          protocol: TCP
      volumes:
      - name: ofrecord-fs
        hostPath: 
          path: /nfs
          type: Directory
      - name: dubhe-data-process
        hostPath:
          path: /dubhe_data_process
          type: Directory    
