spring:
  # serving预测上传文件大小限制
  servlet:
    multipart:
      # 设置单个文件的大小
      max-file-size: 10MB
      # 设置单次请求的文件的总大小
      max-request-size: 100MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能，利用微服务名进行路由


#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

serving:
  gateway:
    # 在线服务http接口 host:port,解析地址为serving网关部署的服务地址
    postfixUrl: 10.101.12.41:8081
    token:
      secret-key: 1n3512x
      expire-seconds: 108000
    corePoolSize: 10
    httpclient:
      connect-timeout: 1000
      response-timeout: 3000
#关闭熔断机制
feign:
  hystrix:
    enabled: false