#配置数据源
spring:
  redis:
    #数据库索引
    database: 1
    host: 10.5.26.88
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
  # 配置允许后面的Bean覆盖前面名称重复的Bean
  main:
    allow-bean-definition-overriding: true

model:
  atlas:
    url:
      # 流服务地址
      rtmp: rtmp://10.5.30.42:1935/live/
      # vms接口地址
      vms: http://10.105.10.51:8000/api/vms
      # 推理服务地址
      video-serve: http://10.105.0.6:32761/video
      # 拉流地址，需要拼接streamId
      stream: http://10.5.30.42:8055/live?port=1935&app=live&stream=
